### ISSUE TITLE
Any ways to create BevelFilter?

### ISSUE THREAD

**Issue by CrazyFlasher** [devon-o/Starling-Filters#10]
Hi, are there any ready implementations of BevelFilter?
Something like in native flash display list?
![gif](https://user-images.githubusercontent.com/1607138/35758583-6f6dede8-087d-11e8-81fb-5e3ac5e486ef.gif)
![32aaacf545](https://user-images.githubusercontent.com/1607138/35758588-78e4fefc-087d-11e8-905a-398588e85778.png)

**Comment by devon-o** [comment]
Hey CrazyFlasher,
You might want to check out the Starling dynamic lighting extension - I think that would help create the effect you're looking for: http://wiki.starling-framework.org/extensions/dynamic_lighting

That said, I may dig into this further later and see what I can come up with.
-d.

**Comment by CrazyFlasher** [comment]
Thanks for quick reply!
Yes, I know about dynamic lightning. But I have kinematic animation (not sprite sheet) with starling display object tree created with Flump. I cannot create normal maps in my case

**Comment by CrazyFlasher** [comment]
Btw, I can pay for current filter implementation, and I don't mind if you'll open source it.
If you are interested - mail me anton@javelin.ee or find me in Facebook: Anton CrazyFlasher Nefjodov.
Thanks in advance :)

**Comment by devon-o** [comment]
Radio Silence.
