### ISSUE TITLE
FlashlightFilter only work on 0,0 (Starling v2.3)

### ISSUE THREAD

**Issue by tadeubas** [devon-o/Starling-Filters#11]
I am trying to create a flashlight that moves around my Sprite, but when I **change the x or y properties, the flashlight effect disappear**. Creating the filter with x or y not equal to zero also does not render...

```as3
public class Game extends Sprite {
...

var flash:FlashlightFilter = new FlashlightFilter(0,0,45);

this.filter = flash;

...
```

[Starling] Context ready. Display Driver: DirectX11 (Baseline Extended)

Tested with SDK AIR 28.0.0 or SDK Flex 4.6.0, AIR 3.1 with same results...

**Comment by devon-o** [comment]
Hello Tudumanu,

I just tried, but could not reproduce the problem. What values are you using x & y? The filter x/y values should range from (0,0) - top left corner - to (1,1) - bottom right corner.

-Devon

**Comment by tadeubas** [comment]
I was setting the values  too high! You could add a hint on the code:
```as3
FlashlightFilter.as


/**
     * Create a new Flashlight Filter
     * @param x     x position. 0 left corner, 1 right corner
     * @param y     y position. 0 top corner, 1 bottom corner
     * @param angle angle of light cone
     */
    public function FlashlightFilter(x:Number=0.0, y:Number=0.0, angle:Number=0.0) 
    {
        this._x = x;
        this._y = y;
        this._angle = angle;
        
        super();
    }
```

Thx for the tip!
