### ISSUE TITLE
Error #3753: Rectangle or cube textures require textures sampling to be set to clamp.

### ISSUE THREAD

**Issue by cgascons** [devon-o/Starling-Filters#2]
Hi there!

I got into an error I really don't understand and I thought I'd ask here! The thing is that I'm using a SineFilter on a 64x64 image on my game and it just goes fine when playing on a 1x textures device (non-retina), but when I try to do exactly the same with a 2x device (128x128 image) the Context3D crashes showing the following error:

Error #3753: Rectangle or cube textures require textures sampling to be set to clamp.
	at flash.display3D::Context3D/drawTriangles()

I don't quite understand the error because it's actually using the same texture size but only on a 2x device (this happens even on the pc simulator).

Hope you can help me with this! And thank you by the way for such nice Filters you have made!

**Comment by devon-o** [comment]
I believe this is the same issue that was seen here: https://github.com/devon-o/Starling-Filters/issues/5 . I'm going to close this for now (yes, it's been a very long time), but if the issue persists after checking on the RectangleTexture fix, reopen.
