### ISSUE TITLE
RectMaskFilter.as is missing

### ISSUE THREAD

**Issue by 22Round** [devon-o/Starling-Filters#7]
quite old tread 
[invert a ClipRect (cut hole in object)](http://forum.starling-framework.org/topic/invert-a-cliprect-cut-hole-in-object) but...
have a same issue and can't find **RectMaskFilter.as** class or is it renaimed?

**Comment by devon-o** [comment]
Hi 22Round,

Sorry for the delay - I missed this issue. The RectMaskFilter was removed after Stencil Masks were added to Starling. It was created mostly as a demo anyway and probably should not have been added to the repo. Having said that, though, you can still view it in the history and are welcome to use it at your own risk: https://github.com/devon-o/Starling-Filters/commit/7327a78316d7b88358157868a10cd1f3fd9e50e3

-devon
