### ISSUE TITLE
Compatible for Starling V2?

### ISSUE THREAD

**Issue by TimKoppers** [devon-o/Starling-Filters#8]
Hi Devon,

I was wondering if this filter will be compatible with the new release V2 of Starling ?

All the best!

**Comment by 22Round** [comment]
there is already V2 branch

**Comment by TimKoppers** [comment]
Thanks! I'm looking for the spotlightfilter, is that the same as the flashlightfilter? Or is that filter not updated yet?

**Comment by devon-o** [comment]
SpotlightFilter has not been updated yet. Will have it this weekend.

**Comment by devon-o** [comment]
Spotlight filter has now been added. Going to close this now.
